export const orderColumns = [
  {
    field: 'expand_action',
    headerName: '',
    sortable: false,
    sort: false,
  },
  {
    field: 'order_name',
    headerName: 'Bestellung',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'from',
    headerName: 'Von',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'costumer',
    headerName: 'Kunde',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'tags',
    headerName: 'Tags',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'payment',
    headerName: 'Zahlung',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'amount',
    headerName: 'Betrag (brutto)',
    sortable: false,
    sort: true,
  },
  {
    field: 'shipping_method',
    headerName: 'Versandart',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'status',
    headerName: 'Status',
    sortable: false,
    sort: true,
    search: true,
  },
  {
    field: 'filter_monitor',
    headerName: 'Monitor',
    sortable: false,
    sort: false,
  },
  {
    field: 'actions',
    headerName: '',
    sortable: false,
    sort: false,
  },
];
